/*
 * Nyagua - Aquarium Manager
 *    Copyright (C) 2012 Rudi Giacomini Pilon
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * 
 */


package util_panels;

import nyagua.ContextMenuMouseListener;
import nyagua.LocUtil;
import nyagua.Util;

/*
 * ConvertersPanel.java interface to converters
 * used to convert some units on some others
 *
 * Created on 4-gen-2013, 13.51.54
 *
 *
 * @author rudigiacomini
 */
public class ConvertersPanel extends javax.swing.JPanel {

    /** Creates new form ConvertersPanel */
    public ConvertersPanel() {
        initComponents();
        initLenght();
        initVolume();
        initTemperature();
        initMass();
        initCutAndPaste();  
    }
    
    //load items on Leght combo
    private void initLenght(){
        lenghtComboBox.addItem("cm --> inch");//NOI18N  //0
        lenghtComboBox.addItem("inch --> cm");//NOI18N  //1
        lenghtComboBox.addItem("cm --> feet");//NOI18N  //2
        lenghtComboBox.addItem("feet --> cm");//NOI18N  //3
    }
    
    //load items on Volume combo
    private void initVolume(){
        volumeComboBox.addItem("l --> US gal");//NOI18N  //0
        volumeComboBox.addItem("US gal --> l");//NOI18N  //1
        volumeComboBox.addItem("l --> cc");//NOI18N  //2
        volumeComboBox.addItem("cc --> l");//NOI18N  //3
        volumeComboBox.addItem("l --> ci");//NOI18N  //4
        volumeComboBox.addItem("ci --> l");//NOI18N  //5
        volumeComboBox.addItem("ci --> US gal");//NOI18N  //6
        volumeComboBox.addItem("US gal --> ci");//NOI18N  //7
        volumeComboBox.addItem("cc --> US gal");//NOI18N  //8
        volumeComboBox.addItem("US gal --> cc");//NOI18N  //9
        volumeComboBox.addItem("cc --> tsp");//NOI18N  //8
        volumeComboBox.addItem("tsp --> cc");//NOI18N  //9
    }
    
    //load items on Temperature combo
    private void initTemperature(){
        temperatureComboBox.addItem("Celsius --> Fahrenheit");//NOI18N  //0
        temperatureComboBox.addItem("Fahrenheit --> Celsius");//NOI18N  //1
        temperatureComboBox.addItem("Celsius --> Kelvin");//NOI18N  //2
        temperatureComboBox.addItem("Kelvin --> Celsius");//NOI18N  //3
        temperatureComboBox.addItem("Kelvin --> Fahrenheit");//NOI18N  //4
        temperatureComboBox.addItem("Fahrenheit --> Kelvin");//NOI18N  //5
    }
    
    //load items on Mass combo
    private void initMass(){
        massComboBox.addItem("g --> oz");//NOI18N  //0
        massComboBox.addItem("oz --> g");//NOI18N  //1
        massComboBox.addItem("kg --> lb");//NOI18N  //2
        massComboBox.addItem("lb --> kg");//NOI18N  //3
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lenghtPanel = new javax.swing.JPanel();
        fromLLabel = new javax.swing.JLabel();
        fromLTextField = new javax.swing.JTextField();
        lenghtComboBox = new javax.swing.JComboBox();
        toLLabel = new javax.swing.JLabel();
        toLTextField = new javax.swing.JTextField();
        calcLenghtButton = new javax.swing.JButton();
        volumePanel = new javax.swing.JPanel();
        fromVLabel = new javax.swing.JLabel();
        fromVTextField = new javax.swing.JTextField();
        volumeComboBox = new javax.swing.JComboBox();
        toVLabel = new javax.swing.JLabel();
        toVTextField = new javax.swing.JTextField();
        calcVolumeButton = new javax.swing.JButton();
        temperaturePanel = new javax.swing.JPanel();
        fromTLabel = new javax.swing.JLabel();
        fromTTextField = new javax.swing.JTextField();
        temperatureComboBox = new javax.swing.JComboBox();
        toTLabel = new javax.swing.JLabel();
        toTTextField = new javax.swing.JTextField();
        calcTemperatureButton = new javax.swing.JButton();
        massPanel = new javax.swing.JPanel();
        fromMLabel = new javax.swing.JLabel();
        fromMTextField = new javax.swing.JTextField();
        massComboBox = new javax.swing.JComboBox();
        toMLabel = new javax.swing.JLabel();
        toMTextField = new javax.swing.JTextField();
        calcMassButton = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("nyagua/Bundle"); // NOI18N
        lenghtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("length"))); // NOI18N

        fromLLabel.setText(bundle.getString("FROM")); // NOI18N

        fromLTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fromLTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromLTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fromLTextFieldKeyReleased(evt);
            }
        });

        toLLabel.setText(bundle.getString("TO")); // NOI18N

        toLTextField.setEditable(false);
        toLTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        calcLenghtButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator2.png"))); // NOI18N
        calcLenghtButton.setToolTipText(bundle.getString("Calc")); // NOI18N
        calcLenghtButton.setAlignmentY(0.0F);
        calcLenghtButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcLenghtButton.setEnabled(false);
        calcLenghtButton.setMaximumSize(new java.awt.Dimension(42, 42));
        calcLenghtButton.setMinimumSize(new java.awt.Dimension(42, 42));
        calcLenghtButton.setPreferredSize(new java.awt.Dimension(42, 42));
        calcLenghtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcLenghtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lenghtPanelLayout = new javax.swing.GroupLayout(lenghtPanel);
        lenghtPanel.setLayout(lenghtPanelLayout);
        lenghtPanelLayout.setHorizontalGroup(
            lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lenghtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lenghtPanelLayout.createSequentialGroup()
                        .addComponent(fromLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lenghtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fromLLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcLenghtButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lenghtPanelLayout.setVerticalGroup(
            lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lenghtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lenghtPanelLayout.createSequentialGroup()
                        .addGroup(lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromLLabel)
                            .addComponent(toLLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lenghtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lenghtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calcLenghtButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 15);
        add(lenghtPanel, gridBagConstraints);

        volumePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("volume"))); // NOI18N

        fromVLabel.setText(bundle.getString("FROM")); // NOI18N

        fromVTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fromVTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromVTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fromVTextFieldKeyReleased(evt);
            }
        });

        toVLabel.setText(bundle.getString("TO")); // NOI18N

        toVTextField.setEditable(false);
        toVTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        calcVolumeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator2.png"))); // NOI18N
        calcVolumeButton.setToolTipText(bundle.getString("Calc")); // NOI18N
        calcVolumeButton.setAlignmentY(0.0F);
        calcVolumeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcVolumeButton.setEnabled(false);
        calcVolumeButton.setMaximumSize(new java.awt.Dimension(42, 42));
        calcVolumeButton.setMinimumSize(new java.awt.Dimension(42, 42));
        calcVolumeButton.setPreferredSize(new java.awt.Dimension(42, 42));
        calcVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcVolumeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout volumePanelLayout = new javax.swing.GroupLayout(volumePanel);
        volumePanel.setLayout(volumePanelLayout);
        volumePanelLayout.setHorizontalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(volumePanelLayout.createSequentialGroup()
                        .addComponent(fromVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(volumeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fromVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcVolumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        volumePanelLayout.setVerticalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcVolumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(volumePanelLayout.createSequentialGroup()
                        .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromVLabel)
                            .addComponent(toVLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        add(volumePanel, gridBagConstraints);

        temperaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("temperature"))); // NOI18N

        fromTLabel.setText(bundle.getString("FROM")); // NOI18N

        fromTTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fromTTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromTTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fromTTextFieldKeyReleased(evt);
            }
        });

        toTLabel.setText(bundle.getString("TO")); // NOI18N

        toTTextField.setEditable(false);
        toTTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        calcTemperatureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator2.png"))); // NOI18N
        calcTemperatureButton.setToolTipText(bundle.getString("Calc")); // NOI18N
        calcTemperatureButton.setAlignmentY(0.0F);
        calcTemperatureButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcTemperatureButton.setEnabled(false);
        calcTemperatureButton.setMaximumSize(new java.awt.Dimension(42, 42));
        calcTemperatureButton.setMinimumSize(new java.awt.Dimension(42, 42));
        calcTemperatureButton.setPreferredSize(new java.awt.Dimension(42, 42));
        calcTemperatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcTemperatureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temperaturePanelLayout = new javax.swing.GroupLayout(temperaturePanel);
        temperaturePanel.setLayout(temperaturePanelLayout);
        temperaturePanelLayout.setHorizontalGroup(
            temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(temperaturePanelLayout.createSequentialGroup()
                        .addComponent(fromTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(temperatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fromTLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toTLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcTemperatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        temperaturePanelLayout.setVerticalGroup(
            temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcTemperatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(temperaturePanelLayout.createSequentialGroup()
                        .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromTLabel)
                            .addComponent(toTLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        add(temperaturePanel, gridBagConstraints);

        massPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mass"))); // NOI18N

        fromMLabel.setText(bundle.getString("FROM")); // NOI18N

        fromMTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fromMTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromMTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fromMTextFieldKeyReleased(evt);
            }
        });

        toMLabel.setText(bundle.getString("TO")); // NOI18N

        toMTextField.setEditable(false);
        toMTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        calcMassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator2.png"))); // NOI18N
        calcMassButton.setToolTipText(bundle.getString("Calc")); // NOI18N
        calcMassButton.setAlignmentY(0.0F);
        calcMassButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcMassButton.setEnabled(false);
        calcMassButton.setMaximumSize(new java.awt.Dimension(42, 42));
        calcMassButton.setMinimumSize(new java.awt.Dimension(42, 42));
        calcMassButton.setPreferredSize(new java.awt.Dimension(42, 42));
        calcMassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcMassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout massPanelLayout = new javax.swing.GroupLayout(massPanel);
        massPanel.setLayout(massPanelLayout);
        massPanelLayout.setHorizontalGroup(
            massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(massPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(massPanelLayout.createSequentialGroup()
                        .addComponent(fromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(massComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fromMLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toMLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        massPanelLayout.setVerticalGroup(
            massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(massPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(massPanelLayout.createSequentialGroup()
                        .addGroup(massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromMLabel)
                            .addComponent(toMLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(massPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(massComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 15);
        add(massPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void fromLTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromLTextFieldKeyPressed
// allow only numbers and related chars
    Util.checkNumericKey(evt);
}//GEN-LAST:event_fromLTextFieldKeyPressed

private void calcLenghtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcLenghtButtonActionPerformed
// Lenght conversions:
    double from=Double.valueOf(LocUtil.delocalizeDouble(fromLTextField.getText()));
    double to=0;
    switch (lenghtComboBox.getSelectedIndex()){
        case 0: to=Converter.cm2inch(from);
            break;
        case 1: to =Converter.inch2cm(from);
            break;
        case 2: to=Converter.cm2feet(from);
            break;
        case 3: to =Converter.feet2cm(from);
            break;   
    }
    toLTextField.setText(LocUtil.localizeDouble(to));
}//GEN-LAST:event_calcLenghtButtonActionPerformed

private void fromVTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromVTextFieldKeyPressed
// allow only numbers and related chars
    Util.checkNumericKey(evt);
}//GEN-LAST:event_fromVTextFieldKeyPressed

private void calcVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcVolumeButtonActionPerformed
// Volume conversions:
    double from=Double.valueOf(LocUtil.delocalizeDouble(fromVTextField.getText()));
    double to=0;
    switch (volumeComboBox.getSelectedIndex()){
        case 0: to=Converter.l2gal(from);
            break;
        case 1: to =Converter.gal2l(from);
            break;
        case 2: to=Converter.l2cc(from);
            break;
        case 3: to =Converter.cc2l(from);
            break;
        case 4: to=Converter.l2ci(from);
            break;
        case 5: to =Converter.ci2l(from);
            break;
        case 6: to=Converter.ci2gal(from);
            break;
        case 7: to =Converter.gal2ci(from);
            break;
        case 8: to=Converter.cc2gal(from);
            break;
        case 9: to =Converter.gal2cc(from);
            break;
        case 10: to=Converter.cc2tsp(from);
            break;
        case 11: to =Converter.tsp2cc(from);
            break;
    }
    toVTextField.setText(LocUtil.localizeDouble(to));
}//GEN-LAST:event_calcVolumeButtonActionPerformed

private void fromTTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromTTextFieldKeyPressed
// allow only numbers and related chars
    Util.checkNumericKey(evt);
}//GEN-LAST:event_fromTTextFieldKeyPressed

private void calcTemperatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcTemperatureButtonActionPerformed
// Temperature conversions:
    double from=Double.valueOf(LocUtil.delocalizeDouble(fromTTextField.getText()));
    double to=0;
    switch (temperatureComboBox.getSelectedIndex()){
        case 0: to=Converter.C2F(from);
            break;
        case 1: to =Converter.F2C(from);
            break;
        case 2: to=Converter.C2K(from);
            break;
        case 3: to =Converter.K2C(from);
            break;
        case 4: to=Converter.K2F(from);
            break;
        case 5: to =Converter.F2K(from);
            break;    
           
    }
    toTTextField.setText(LocUtil.localizeDouble(to));
}//GEN-LAST:event_calcTemperatureButtonActionPerformed

private void fromMTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromMTextFieldKeyPressed
// allow only numbers and related chars
    Util.checkNumericKey(evt);
}//GEN-LAST:event_fromMTextFieldKeyPressed

private void calcMassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcMassButtonActionPerformed
// Mass conversions:
    double from=Double.valueOf(LocUtil.delocalizeDouble(fromMTextField.getText()));
    double to=0;
    switch (massComboBox.getSelectedIndex()){
        case 0: to=Converter.g2oz(from);
            break;
        case 1: to =Converter.oz2g(from);
            break;
        case 2: to=Converter.kg2lb(from);
            break;
        case 3: to =Converter.lb2kg(from);
            break;
        }
    toMTextField.setText(LocUtil.localizeDouble(to));
}//GEN-LAST:event_calcMassButtonActionPerformed

    private void fromLTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromLTextFieldKeyReleased
        // check values
        calcLenghtButton.setEnabled(Util.CheckTestFields(fromLTextField));
    }//GEN-LAST:event_fromLTextFieldKeyReleased

    private void fromVTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromVTextFieldKeyReleased
        // check values
        calcVolumeButton.setEnabled(Util.CheckTestFields(fromVTextField));
    }//GEN-LAST:event_fromVTextFieldKeyReleased

    private void fromTTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromTTextFieldKeyReleased
        // check values
        calcTemperatureButton.setEnabled(Util.CheckTestFields(fromTTextField));
    }//GEN-LAST:event_fromTTextFieldKeyReleased

    private void fromMTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromMTextFieldKeyReleased
        // check values
        calcMassButton.setEnabled(Util.CheckTestFields(fromMTextField));
    }//GEN-LAST:event_fromMTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcLenghtButton;
    private javax.swing.JButton calcMassButton;
    private javax.swing.JButton calcTemperatureButton;
    private javax.swing.JButton calcVolumeButton;
    private javax.swing.JLabel fromLLabel;
    private javax.swing.JTextField fromLTextField;
    private javax.swing.JLabel fromMLabel;
    private javax.swing.JTextField fromMTextField;
    private javax.swing.JLabel fromTLabel;
    private javax.swing.JTextField fromTTextField;
    private javax.swing.JLabel fromVLabel;
    private javax.swing.JTextField fromVTextField;
    private javax.swing.JComboBox lenghtComboBox;
    private javax.swing.JPanel lenghtPanel;
    private javax.swing.JComboBox massComboBox;
    private javax.swing.JPanel massPanel;
    private javax.swing.JComboBox temperatureComboBox;
    private javax.swing.JPanel temperaturePanel;
    private javax.swing.JLabel toLLabel;
    private javax.swing.JTextField toLTextField;
    private javax.swing.JLabel toMLabel;
    private javax.swing.JTextField toMTextField;
    private javax.swing.JLabel toTLabel;
    private javax.swing.JTextField toTTextField;
    private javax.swing.JLabel toVLabel;
    private javax.swing.JTextField toVTextField;
    private javax.swing.JComboBox volumeComboBox;
    private javax.swing.JPanel volumePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * bind cutandpaste popup menu to text fields
     */
    private void initCutAndPaste(){
        fromLTextField.addMouseListener(new ContextMenuMouseListener());
        fromMTextField.addMouseListener(new ContextMenuMouseListener());
        fromTTextField.addMouseListener(new ContextMenuMouseListener());
        fromVTextField.addMouseListener(new ContextMenuMouseListener());
    }
}
