/*
 * Nyagua - Aquarium Manager
 *    Copyright (C) 2010 Rudi Giacomini Pilon *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package nyagua;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Database Selection form
 * 
 * @author Rudi Giacomini Pilon
 * @version 1.0
 */
public class DBSelector extends javax.swing.JDialog {
    /**This dialog can be colled in 3 ways*/
    public static final int MODE_DB_CREATE = 1;
    public static final int MODE_DB_OPEN = 2;
    public static final int MODE_BOTH = 0;
    private int mode = MODE_BOTH; //default mode show all
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    /** status for window */
    private boolean status=false;


    /** Creates new form DBSelector
     * @param parent
     * @param modal */
    public DBSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        if (Global.FullFileName != null) {
            pathTextField.setText(Global.FullFileName);
        }
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * Set the display operation mode
     *
     * @param modeSel 0=Both / 1= DB create / 2= DB open
     */
    public void setMode(int modeSel){
        this.mode=modeSel;
        switch (mode){
            case MODE_BOTH:
                break;
            case MODE_DB_CREATE:
                messageLabel.setVisible(false);
                DBExistRadioButton.setVisible(false);
                DBNewRadioButton.setVisible(true);
                DBNewRadioButton.setSelected(true);
                break;
            case MODE_DB_OPEN:
                messageLabel.setVisible(false);
                DBExistRadioButton.setVisible(true);
                DBExistRadioButton.setSelected(true);
                DBNewRadioButton.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButtonGroup = new javax.swing.ButtonGroup();
        containerPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        messagePanel = new javax.swing.JPanel();
        DBNewRadioButton = new javax.swing.JRadioButton();
        DBExistRadioButton = new javax.swing.JRadioButton();
        messageLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        pathSelectButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        containerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wiz2.png"))); // NOI18N
        imageLabel.setMaximumSize(new java.awt.Dimension(150, 240));

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_16x.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("nyagua/Bundle"); // NOI18N
        cancelButton.setText(bundle.getString("CANCEL")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        okButton.setText(bundle.getString("Next")); // NOI18N
        okButton.setSelected(true);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        actionButtonGroup.add(DBNewRadioButton);
        DBNewRadioButton.setSelected(true);
        DBNewRadioButton.setText(bundle.getString("DBSelector.DBNewRadioButton.text")); // NOI18N

        actionButtonGroup.add(DBExistRadioButton);
        DBExistRadioButton.setText(bundle.getString("DBSelector.DBExistRadioButton.text")); // NOI18N

        messageLabel.setText(bundle.getString("DBSelector.messageLabel.text")); // NOI18N

        pathSelectButton.setText(bundle.getString("dot_dot_dot")); // NOI18N
        pathSelectButton.setMinimumSize(new java.awt.Dimension(46, 19));
        pathSelectButton.setPreferredSize(new java.awt.Dimension(46, 19));
        pathSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathSelectButtonActionPerformed(evt);
            }
        });

        pathLabel.setText(bundle.getString("PATH")); // NOI18N

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DBExistRadioButton)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(DBNewRadioButton)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pathLabel))
                .addContainerGap())
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DBNewRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DBExistRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        setSize(new java.awt.Dimension(558, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (DBNewRadioButton.isSelected()){
            //Create DB and set path and dir
            String fullFilePath=pathTextField.getText();  
            //check for .db extension (not necessary but useful)
            int endIndex=fullFilePath.lastIndexOf(".");//NOI18N
            if (endIndex<=0){//need to add extension
                fullFilePath=fullFilePath+".db";
            }else {//check for correct extension
                String ext=fullFilePath.substring(endIndex, fullFilePath.length());
                if (!(ext.equalsIgnoreCase(".db"))) { //wrong extension add .db at the end
                    fullFilePath=fullFilePath+".db";
                }
            }
                
            //end check .db extension
            if (fullFilePath == null) {
                messageLabel.setVisible(true);
                return;
            }
            File f = new File (fullFilePath);
            //if f is a directory need to add default filename
            if (f.isDirectory()){
                //check if fileseparator is included
                if (!fullFilePath.endsWith(Application.FS)){
                    fullFilePath=fullFilePath + Application.FS;
                } 
                fullFilePath=fullFilePath + Application.DATA_FILENAME;
            }

            Global.FullFileName=fullFilePath;
            boolean result=DB.createNewDB();
            if (result) {
                //new db created sucessfully
                DBExistRadioButton.setEnabled(false);
                DBNewRadioButton.setEnabled(false);
                pathTextField.setEditable(false);
                pathSelectButton.setEnabled(false);
                cancelButton.setEnabled(false);
                messageLabel.setText(java.util.ResourceBundle.getBundle("nyagua/Bundle").getString("DATABASE_CREATED/UPDATED"));
                if (!status) {
                    //Don't leave the mask before to display the message
                    okButton.setText(java.util.ResourceBundle.getBundle("nyagua/Bundle").getString("OK"));
                    status = true;
                    return;
                }                     
                
            }
        } else {
            //Set paths with selected db
            String fullFilePath=pathTextField.getText();
            if (fullFilePath == null){
                messageLabel.setVisible(true);
                return;
            }
            File f = new File (fullFilePath);
            if (!f.exists()){
                messageLabel.setVisible(true);
                return;
            }
            Global.FullFileName=fullFilePath;
        }
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void pathSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathSelectButtonActionPerformed
        //Select Filename or path
        JFileChooser jfc = new JFileChooser();
        if (DBNewRadioButton.isSelected()){
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jfc.setCurrentDirectory(new File (pathTextField.getText().substring(0,
                    pathTextField.getText().lastIndexOf(Application.FS))));

        } else if (DBExistRadioButton.isSelected()) {
            jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            jfc.setCurrentDirectory(new File (pathTextField.getText().substring(0,
                    pathTextField.getText().lastIndexOf(Application.FS))));
        }        
        int result = jfc.showOpenDialog(null);
        if (result==JFileChooser.APPROVE_OPTION ) {
            pathTextField.setText((jfc.getSelectedFile().getAbsolutePath()));
        } 
    }//GEN-LAST:event_pathSelectButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DBSelector dialog = new DBSelector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DBExistRadioButton;
    private javax.swing.JRadioButton DBNewRadioButton;
    private javax.swing.ButtonGroup actionButtonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton pathSelectButton;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
