/*
 * Nyagua - Aquarium Manager
 *    Copyright (C) 2016 Rudi Giacomini Pilon
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
package nyagua;

import nyagua.data.Aquarium;

/**
 * Welcome window
 * 
 * @author Rudi Giacomini Pilon
 * @version 1.0
 */
public class Welcome extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form Settings
     * @param parent
     * @param modal  
     */
    public Welcome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        okButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        wizPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        welcomeLabel = new javax.swing.JTextArea();
        aquariumNameLabel = new javax.swing.JLabel();
        aquariumNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("nyagua/Bundle"); // NOI18N
        okButton.setText(bundle.getString("Next")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(11, 15, 11, 15);
        getContentPane().add(okButton, gridBagConstraints);

        wizPanel.setAlignmentX(0.0F);
        wizPanel.setAlignmentY(0.0F);
        wizPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        wizPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);

        welcomeLabel.setEditable(false);
        welcomeLabel.setBackground(new java.awt.Color(238, 238, 238));
        welcomeLabel.setColumns(20);
        welcomeLabel.setLineWrap(true);
        welcomeLabel.setRows(5);
        welcomeLabel.setText(bundle.getString("WELCOME1")); // NOI18N
        welcomeLabel.setWrapStyleWord(true);
        welcomeLabel.setBorder(null);
        jScrollPane1.setViewportView(welcomeLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 419;
        gridBagConstraints.ipady = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 15, 12);
        wizPanel.add(jScrollPane1, gridBagConstraints);

        aquariumNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        aquariumNameLabel.setText(bundle.getString("Ny.aquariumNameLabel.text")); // NOI18N
        aquariumNameLabel.setMinimumSize(new java.awt.Dimension(60, 15));
        aquariumNameLabel.setPreferredSize(new java.awt.Dimension(60, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 2);
        wizPanel.add(aquariumNameLabel, gridBagConstraints);

        aquariumNameTextField.setMinimumSize(new java.awt.Dimension(30, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 349;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        wizPanel.add(aquariumNameTextField, gridBagConstraints);

        jTabbedPane1.addTab(bundle.getString("Start.here"), wizPanel); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.weighty = 4.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 10, 15);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wiz3.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        setSize(new java.awt.Dimension(652, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Saves Settings */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        if (!aquariumNameTextField.getText().isEmpty()) { //name given
            Aquarium tank=new Aquarium();
            tank.setId(0);
            tank.setName(aquariumNameTextField.getText());
            Aquarium.save(tank);
        }
        
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aquariumNameLabel;
    private javax.swing.JTextField aquariumNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea welcomeLabel;
    private javax.swing.JPanel wizPanel;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;    
    
}
